spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fis
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/changelog-main.yaml
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
  file:
   name: /var/log/fis/kabinet.log
server:
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    application-display-name: Личный кабинет ФИС Услуги
  tomcat:
    accesslog:
      directory: /var/log/fis
mybatis:
  config-location: classpath:mybatis-config.xml
bitrix24:
  domain: ${bitrix.domain}
  user-id: ${bitrix.user-id}
  token: ${bitrix.apikey}
  country: ${bitrix.country}
  responsible-id: ${bitrix.responsible}
minio:
  bucket: default
  accesskey: fiskabinet
  secretkey: 12345678
  url: http://localhost/
  port: 9000
deploy:
  host: http://localhost:8080/
  version: 0.5.100