spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fis
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/changelog-main.yaml
logging:
  level:
    org:
      springframework:
        security: DEBUG
mybatis:
#  type-aliases-package: ru.antelit.fiskabinet.domain
  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:ru/antelit/fiskabinet/service/dao/*
server:
  error:
    whitelabel:
      enabled: true