spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fis
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/changelog-main.yaml
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
mybatis:
  config-location: classpath:mybatis-config.xml
server:
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    application-display-name: Личный кабинет ФИС Услуги
bitrix24:
  domain: antelplus
  user-id: 21
  token: b38vyanz2vyjj67m
  country: ru
  responsible-id: 21
minio:
  bucket: default
  accesskey: fiskabinet
  secretkey: 12345678
  url: http://localhost/
  port: 9000
deploy:
  host: http://localhost:8080/
  version: 0.5.100