spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fis
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/changelog-main.yaml
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
mybatis:
  config-location: classpath:mybatis-config.xml
# type-aliases-package: ru.antelit.fiskabinet.domain
# mapper-locations: classpath:ru/antelit/fiskabinet/service/dao/*
server:
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    application-display-name: Личный кабинет ФИС Услуги
